### ISSUE TITLE
Team Selector Not Functioning in /kit Command

### ISSUE THREAD

**Issue by moraedu** [DogLoverPink/EssentialsX-Target-Selectors#12] opened 2023-09-18 11:59 UTC
**What went wrong?**
I cannot use the "team" selector in the "/kit" command (and I believe in some other commands as well).

**Steps to reproduce:**
1. Create a team and a kit (use the commands /team add test & /createkit test).
2. Join the newly created team (/team join test).
3. Execute the following commands:
   - `/kit test @a[team=test]` <- This command doesn't work.
   - `/kit test @a[team=!test]` <- This command gives the kit to all connected players, including those in the specified team.

**Any errors in console? If so, post the full error here, or post it on [this](https://mclo.gs/) website and share the link.**
No errors were logged in the console.

**What is your plugin, server, and Java version?**
- Plugin: 1.7.2
- EssentialsX: 2.20.1
- Server: 1.17.1
- Java: 16

**Anything else?**
I believe there might be some other commands, aside from /kit, that may not work correctly with the "team" selector, but I can't recall which ones at the moment.

**Comment by DogLoverPink** [comment] 2023-09-20 18:42
Hmm, Unfortunately I was not able to reproduce this issue. It would be appreciated if you could list all the plugins that your server uses so that I can do further analysis.

Thank you for reporting!

**Comment by moraedu** [comment] 2023-09-20 19:50
I forgot to mention that I am using PaperMC software for my server. I just noticed that when I start the plugin, I receive a warning, but I don't think it's the cause of the problem:
`[Server thread/WARN]: [Essentials] Version mismatch! Please update EssentialsSelectors to the same version.`



> Hmm, Unfortunately I was not able to reproduce this issue. It would be appreciated if you could list all the plugins that your server uses so that I can do further analysis.
> 
> Thank you for reporting!

Plugin list:
- EssentialsX 2.20.1
- EssentialsX Chat 2.20.1
- EssentialsX Target Selectors 1.7.2
- LoginSecurity 3.2.1-Spigot
- LuckPerms 5.4.102-Bukkit
- Multiverse-Core 4.3.12
- PlaceholderAPI 2.11.3
- SkinsRestorer 14.2.12
- Vault 1.7.3
- ViaVersion 4.7.0
- ViaBackwards 4.7.0
- ViaRewind 2.0.3
- ViaVersionStatus 3.13
- WorldEdit 7.2.15-Bukkit
- WorldGuard 7.0.7-Bukkit

**Comment by DogLoverPink** [comment] 2023-09-20 23:14
I have tested a server with all of the plugins listed, and unfortunately I still could not replicate the issue. The issue you are describing however, seems as if you are not actually on the team, so I would recommend doing `/team list test` before testing again to make sure. If that still does not work, I may rewrite the internal workings of the plugin, as it is due for a rewrite anyway.

The warning in console you got does not mean anything important, as it is only there because the name of the plugin starts with "Essentials," and EssX detects that as an addon, and the versions don't match.

Thank you for providing detailed information on issue, and I'm sorry I couldn't identify the issue and fix it.

**Comment by moraedu** [comment] 2023-09-22 19:00
I have found out that it only happens when the team id has upper case letters, otherwise it works fine. I believe it is because of this part of the code:
https://github.com/DogLoverPink/EssentialsX-Target-Selectors/blob/d468154fecdb105625ffefb7a7444aca84e0ab95/essentialsx_target_selectors/src/main/java/dogloverpink/Events/ServerCommandExecute.java#L85-L87
Here you are checking if the selector isn't `tag` and if so, getting the value and afterwards making it lower case, however tags aren't the only one case-sensitive selector.

**Comment by DogLoverPink** [comment] 2023-09-24 17:57
Oops, I didn't mean to close this. I will close in a few days or if you can confirm that your issue has been fixed.

Thanks for reporting!

**Closed** 2024-05-24 15:52 UTC
Labels: bug
